language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

matrix:
  fast_finish: true

install:
  - travis_retry composer update --no-interaction --prefer-source

script: vendor/bin/phpunit -v --coverage-text